### ISSUE TITLE
Setup a GitHub Actions workflow

### ISSUE THREAD

**Issue by slarse** [repobee/repobee-reviewothers#1]
To run the tests and any other sanity checks

**Comment by dmusican** [comment]
Agreed. Did you say that you were putting together a PR for that? I'm happy to do so otherwise.

**Comment by slarse** [comment]
If you feel like doing it you can go ahead! Otherwise I can do it ~mid next week, I've done it so many times that it'll just take a few minutes.

**Comment by dmusican** [comment]
Then sure, go ahead and do it whenever you've got time to do so. Thanks!

**Comment by slarse** [comment]
woops, I totally forgot about this. Will fix tonight :)
